### ISSUE TITLE
Hi, there

### ISSUE THREAD

**Issue by lianqiann** [mingdachen/vsl#2]
The work is impressive. Can I know which inputs are used for process_twitter_data.py? The default files in ark-tweet-nlp all report format errors

**Comment by mingdachen** [comment]
Hi, thanks for your interests! Yea, I think you are right. I used data files processed by other people. Here are the files that should be ok to use:

[twitter.dev.txt](https://github.com/mingdachen/vsl/files/4500407/twitter.dev.txt)
[twitter.test.txt](https://github.com/mingdachen/vsl/files/4500408/twitter.test.txt)
[twitter.train.txt](https://github.com/mingdachen/vsl/files/4500409/twitter.train.txt)

I'm not 100% sure if these are correct files since the experiments were long time ago, but I am able to process these file with current codebase. I also double-checked the number of instances, which look correct.

Let me know if there are other problems.

**Comment by lianqiann** [comment]
Thank you! This issue is solved. :)
